name: build

run-name: Build

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build and export
        uses: docker/build-push-action@v6.12.0
        with:
          tags: dependabot_pip_websockets:latest
          outputs: type=docker,dest=${{ runner.temp }}/myimdependabot_pip_websockets.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: dependabot_pip_websockets
          path: ${{ runner.temp }}/dependabot_pip_websockets.tar
